variables:
  location: "eastus2"
  ManagementGroupPrefix: "nx"
  serviceConnectionName: "nx-devops-mgmt"

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    displayName: "Deploy CAF Monitoring ARM template"
    inputs:
      azureSubscription: ${{ variables['serviceConnectionName'] }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        ls -la
        az deployment mg create --template-uri ../src/deploy/lz.param.jsonsrc/deploy/lz.json --location $(location) --management-group-id $(ManagementGroupPrefix) --parameters ../src/deploy/lz.param.jsonsrc/deploy/lz.jsonsrc/deploy/lz.param.json