trigger: none

variables:
  location: "eastus2"
  ManagementGroupPrefix: "Examworks"
  serviceConnectionName: "nx-devops-mgmt"

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureFileCopy@3
    inputs:
      SourcePath: 'src/deploy/lz'
      azureSubscription: 'nx-devops'
      Destination: 'AzureBlob'
      storage: 'staarm'
      ContainerName: 'monitoring-buildartifacts'
      outputStorageUri: artifactsLocation
      outputStorageContainerSasToken: artifactsLocationSasToken
        
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Management Group'
      azureResourceManagerConnection: 'nx-devops-mgmt'
      location: 'East US 2'
      templateLocation: 'Linked artifact'
      csmFile: 'src/deploy/lz/lz.json'
      csmParametersFile: 'src/deploy/lz/lz.param.json'
      deploymentMode: 'Incremental'
  