trigger: none

variables:
  location: "eastus2"
  ManagementGroupPrefix: "Examworks"
  serviceConnectionName: "nx-devops-mgmt"

pool:
  vmImage: windows-latest

steps:

  - task: AzureCLI@2
    displayName: "Deploy CAF Monitoring ARM template"
    inputs:
      azureSubscription: ${{ variables['serviceConnectionName'] }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment mg create --template-uri "https://staarm.blob.core.windows.net/monitoring-buildartifacts/lz.json" --location eastus2 --management-group-id Examworkq --parameters src/deploy/lz/lz.param.json --query-string "sp=r&st=2024-02-08T17:26:33Z&se=2024-02-23T01:26:33Z&spr=https&sv=2022-11-02&sr=c&sig=n6lWRZ77veZM%2Fjo4sseXqtntyjSPaobXNYAGHeOk9js%3D"
          
  - task: AzureFileCopy@3
    inputs:
      SourcePath: 'src/deploy/lz'
      azureSubscription: 'nx-devops'
      Destination: 'AzureBlob'
      storage: 'staarm'
      ContainerName: 'monitoring-buildartifacts'
      outputStorageUri: 'artifactsLocation'
      outputStorageContainerSasToken: 'artifactsLocationSasToken'
      sasTokenTimeOutInMinutes: '10'

  - task: AzureCLI@2
    displayName: "Deploy CAF Monitoring ARM template"
    inputs:
      azureSubscription: ${{ variables['serviceConnectionName'] }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment mg create  \
        --management-group-id $(ManagementGroupPrefix) \
        --template-uri $(artifactsLocation)lz.json \
        --query-string $(artifactsLocationSasToken) \
        --location $(location) \
        --parameters src/deploy/lz/lz.param.json 
