trigger: none

variables:
  location: "eastus2"
  ManagementGroupPrefix: "Examworks"
  serviceConnectionName: "nx-devops-mgmt"

pool:
  vmImage: windows-latest

steps:

  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email pipeline@demo.com & git config --global user.name "Pipeline"
      ls -la
    workingDirectory: $(System.DefaultWorkingDirectory)\caf-monitoring

  - script: |
      git checkout -b main
      echo 'This is a test' > data.txt
      git add -A
      git commit -m "deployment $(Build.BuildNumber)"
      git push --set-upstream origin main 
    displayName: Add data.txt file
    workingDirectory: $(System.DefaultWorkingDirectory)\caf-monitoring

  - task: AzureFileCopy@3
    inputs:
      SourcePath: 'src/deploy/lz'
      azureSubscription: 'nx-devops'
      Destination: 'AzureBlob'
      storage: 'staarm'
      ContainerName: 'monitoring-buildartifacts'
      outputStorageUri: 'artifactsLocation'
      outputStorageContainerSasToken: 'artifactsLocationSasToken'
      sasTokenTimeOutInMinutes: '10'

  - task: AzureCLI@2
    displayName: "Deploy CAF Monitoring ARM template"
    inputs:
      azureSubscription: ${{ variables['serviceConnectionName'] }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment mg create --template-uri $(artifactsLocation)lz.json --location $(location) --management-group-id $(ManagementGroupPrefix) --parameters src/deploy/lz/lz.param.json

  - task: AzureCLI@2
    displayName: Remove Artifacts from Storage Account
    condition: always()
    inputs:
      azureSubscription: 'nx-devops'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob delete-batch --source 'monitoring-buildartifacts' --account-name 'staarm' --pattern '*.*'
  
  - checkout: self
    clean: true