trigger: none

variables:
  location: "eastus2"
  ManagementGroupPrefix: "Examworks"
  serviceConnectionName: "nx-devops-mgmt"

pool:
  vmImage: windows-latest

steps:         
  - task: AzureFileCopy@3
    inputs:
      SourcePath: 'src/deploy/lz'
      azureSubscription: 'nx-devops'
      Destination: 'AzureBlob'
      storage: 'staarm'
      ContainerName: 'monitoring-buildartifacts'
      outputStorageUri: 'artifactsLocation'
      outputStorageContainerSasToken: 'artifactsLocationSasToken'
      sasTokenTimeOutInMinutes: '10'

  - task: AzureCLI@2
    displayName: "Deploy CAF Monitoring ARM template"
    inputs:
      azureSubscription: ${{ variables['serviceConnectionName'] }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment mg create --template-uri $(artifactsLocation)lz.json --location $(location) --management-group-id $(ManagementGroupPrefix) --parameters src/deploy/lz/lz.param.json

  - task: AzureCLI@2
    displayName: Remove Artifacts from Storage Account
    condition: always()
    inputs:
      azureSubscription: 'nx-devops'
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: Get-AzureStorageBlob -Container 'monitoring-buildartifacts' -Context 'staarm' | Remove-AzureStorageBlob