trigger: none

variables:
  location: "eastus2"
  ManagementGroupPrefix: "Examworks"
  serviceConnectionName: "nx-devops-mgmt"

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    displayName: "Deploy CAF Monitoring ARM template"
    inputs:
      azureSubscription: ${{ variables['serviceConnectionName'] }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment mg create --template-uri https://raw.githubusercontent.com/midwilshire/caf-monitoring/main/src/deploy/lz/lz.json --location $(location) --management-group-id $(ManagementGroupPrefix) --parameters src/deploy/lz/lz.param.json